### ISSUE TITLE
Circular dependency in build

### ISSUE THREAD

**Issue by avkvirtru** [avkvirtru/virtuoso-design-system#45]
# 🐞 bug report

- [ ] This is a regression and used to work in a previous version -- not sure?

## Description

`npm run build` reports a circular dependency

## 🔬 Steps to Reproduce

- `npm run clean`
- `npm run build`

## 🔥 Exception or Error
<pre><code>
npm run build

> virtuoso-design-system@1.2.0 build /Users/arthurklepchukov/Documents/GitHub/virtuoso-design-system
> rollup --config config/rollup.config.js

lib/components/index.js → dist/bundle.esm.js, dist/bundle.cjs.js...
(!) Circular dependency
lib/components/index.js -> lib/components/Layout/index.js -> lib/components/Layout/BasicLayout.js -> lib/components/Layout/Header.js -> lib/index.js -> lib/components/index.js
created dist/bundle.esm.js, dist/bundle.cjs.js in 5.4s

</code></pre>

## 🌍 Your Environment

**Version:**
<pre><code>
node -pe "require('./package.json').version"
1.2.0

</code></pre>

**Comment by jrschumacher** [comment]
@avkvirtru this is due to the following code. To get around it, imports should be `import A from '@/components/A'` rather than `import { A } from '@'`. Personally I don't mind this and set eslint to allow 1 level of circular dependency.

```js
// lib/index.js
import { default as A } from './components/A';
import { default as B } from './components/B';
export default { A, B };

// lib/components/A/index.js
export default function A() {};


// lib/components/B/index.js
import { A } from '@';

export default function B() { return <A />; };
```

**Comment by avkvirtru** [comment]
No objections here if it's intentional :)
