### ISSUE TITLE
Auto release requires npm without OTP

### ISSUE THREAD

**Issue by jrschumacher** [avkvirtru/virtuoso-design-system#53]
@avkvirtru could you set your npm account to only use OTP on Auth? Or we need to use another account.

https://www.npmjs.com/settings/avkvirtru/profile
![image](https://user-images.githubusercontent.com/46549/90307379-70f24480-de8a-11ea-8b91-9a6b259fa5fa.png)
![image](https://user-images.githubusercontent.com/46549/90307381-73549e80-de8a-11ea-9fa6-6af0b3fd4284.png)

```
npm ERR! code EOTP
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.
```

https://github.com/avkvirtru/virtuoso-design-system/runs/987709488?check_suite_focus=true#step:6:185

**Comment by avkvirtru** [comment]
@jrschumacher switched to auth-only; want to try again and close this if it works?
